---
name: Net-IRC2
version: 0.19
author:
  - Karl Y. Pradene <knotty@cpan.org>
abstract: Client interface to the Internet Relay Chat protocol
license: gpl
requires:
  IO::Socket::INET: 1.27
  Parse::RecDescent: 1.94
  Test::More: ''
  perl: 5.8.1
provides:
  Net::IRC2:
    file: lib/Net/IRC2.pm
    version: 0.19
  Net::IRC2::Connection:
    file: lib/Net/IRC2/Connection.pm
  Net::IRC2::Event:
    file: lib/Net/IRC2/Event.pm
    version: 0.19
  Net::IRC2::Parser:
    file: lib/Net/IRC2/Parser.pm
    version: 0.19
  Parse::RecDescent::Net::IRC2::Parser:
    file: lib/Net/IRC2/Parser.pm
    version: 0.19
generated_by: Module::Build version 0.2611
