---
name: Net-IRC2
version: 0.00_03
author:
  - Karl Y. Pradene <knotty@cpan.org>
abstract: The great new Net::IRC2!
license: gpl
requires:
  IO::Socket::INET: 0
  Parse::RecDescent: 0
  Test::More: 0
  perl: 5.8.1
provides:
  Net::IRC2:
    file: lib/Net/IRC2.pm
    version: 0.00_03
  Net::IRC2::Connection:
    file: lib/Net/IRC2/Connection.pm
    version: 0.00_03
  Net::IRC2::Event:
    file: lib/Net/IRC2/Event.pm
    version: 0.00_03
generated_by: Module::Build version 0.26
