---
name: Net-IRC2
version: 0.05
author:
  - Karl Y. Pradene <knotty@cpan.org>
abstract: ~
license: gpl
requires:
  IO::Socket::INET: 0
  Parse::RecDescent: 0
  Test::More: 0
  perl: 5.8.1
provides:
  Net::IRC2:
    file: lib/Net/IRC2.pm
    version: 0.05
  Net::IRC2::Connection:
    file: lib/Net/IRC2/Connection.pm
    version: 0.05
  Net::IRC2::Event:
    file: lib/Net/IRC2/Event.pm
    version: 0.05
generated_by: Module::Build version 0.26
