#!/usr/bin/perl -w
#
# Copyright 2005, Karl Y. Pradene <knotty@cpan.org> All rights reserved.
#
# Dumb Bot for test Net::IRC2

use Net::IRC2;

use strict; 
use warnings;
$| = 1;
sub p($) { print "@_\n" }


my $bot = new Net::IRC2;

my $conn = $bot->newconn(uri=>'irc://B1-66ER!void@irc.geeknode.org:6667/') || die 'No Connection';
$conn->mode($conn->nick,'+B');
my $sock = $conn->socket;

$bot->callback(\&process_event);
$bot->start;

sub process_event { 
    my $self = shift;
    if ( $self->command eq '376' ) { # END_OF_MOTD
	print "HOOK\n";
#	$conn->join('#Perl');
    }
}

exit 0;


